import React, { useState, useEffect } from 'react';
import { Sparkles, History, ShieldCheck } from 'lucide-react';
import CreditPackageCard from '../components/credits/CreditPackageCard';
import Spinner from '../components/ui/Spinner';
import { useCredits } from '../context/CreditContext';
import { useAuth } from '../context/AuthContext';
import * as creditService from '../services/creditService';
import { formatDate } from '../utils/formatDate';
import toast from 'react-hot-toast';

export default function CreditsPage() {
  const { credits, refreshCredits } = useCredits();
  const { user } = useAuth();

  const [packages, setPackages] = useState([]);
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [purchasingId, setPurchasingId] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const [pkgRes, txRes] = await Promise.all([
          creditService.getPackages(),
          creditService.getTransactions({ limit: 10 }),
        ]);
        setPackages(pkgRes.packages || []);
        setTransactions(txRes.transactions || []);
      } catch (err) {
        console.error('Error fetching credits data:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const loadRazorpay = () => {
    return new Promise((resolve) => {
      if (window.Razorpay) {
        resolve(true);
        return;
      }
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const handlePurchase = async (pkg) => {
    try {
      setPurchasingId(pkg._id);
      const isRzpReady = await loadRazorpay();
      if (!isRzpReady) {
        toast.error('Payment gateway could not be loaded.');
        return;
      }

      // 1. Create order on backend
      const orderRes = await creditService.createOrder(pkg._id);
      const { razorpayOrderId, keyId, amountInPaise, paymentId } = orderRes;

      // 2. Open Razorpay modal
      const options = {
        key: keyId || 'rzp_test_placeholder',
        amount: amountInPaise,
        currency: 'INR',
        name: 'SVARA',
        description: `${pkg.credits} AI Try-On Credits`,
        order_id: razorpayOrderId,
        handler: async (response) => {
          try {
            await creditService.verifyPayment({
              razorpayOrderId: response.razorpay_order_id,
              razorpayPaymentId: response.razorpay_payment_id,
              razorpaySignature: response.razorpay_signature,
              paymentId,
            });
            toast.success(`Success! ${pkg.credits} credits added to your account.`);
            refreshCredits();
            const txRes = await creditService.getTransactions({ limit: 10 });
            setTransactions(txRes.transactions || []);
          } catch {
            toast.error('Payment verification failed.');
          }
        },
        prefill: {
          name: user?.name,
          email: user?.email,
        },
        theme: {
          color: '#C49A3C',
        },
      };

      const rzpInstance = new window.Razorpay(options);
      rzpInstance.open();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to start payment');
    } finally {
      setPurchasingId(null);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-12">
      {/* Current Balance Banner */}
      <div className="glass rounded-3xl p-8 sm:p-12 flex flex-col sm:flex-row items-center justify-between gap-6 border border-white/60">
        <div className="space-y-2 text-center sm:text-left">
          <span className="text-xs font-bold uppercase tracking-widest text-champagne-500">Virtual Wardrobe Power</span>
          <h1 className="font-display text-3xl sm:text-4xl font-bold text-charcoal-700">AI Try-On Credits</h1>
          <p className="text-xs text-charcoal-400 max-w-lg leading-relaxed">
            1 Credit = 1 Virtual Try-On photo generated by our multimodal AI models and saved permanently in your wardrobe.
          </p>
        </div>

        <div className="glass-strong rounded-3xl p-6 text-center shrink-0 border border-champagne-300">
          <span className="text-xs uppercase font-semibold text-charcoal-400 block mb-1">Available Credits</span>
          <div className="font-display text-4xl sm:text-5xl font-extrabold text-champagne-500 flex items-center justify-center gap-2">
            <Sparkles size={28} className="fill-champagne-400 text-champagne-400" />
            <span>{credits}</span>
          </div>
        </div>
      </div>

      {/* Packages Grid */}
      <div className="space-y-6">
        <div className="text-center max-w-lg mx-auto">
          <h2 className="font-display text-2xl font-bold text-charcoal-700">Purchase Credit Packages</h2>
          <p className="text-xs text-charcoal-400 mt-1">Instant activation through safe Indian UPI, Cards, & NetBanking</p>
        </div>

        {loading ? (
          <div className="min-h-[30vh] flex items-center justify-center">
            <Spinner size="lg" />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {packages.map((pkg) => (
              <CreditPackageCard
                key={pkg._id}
                pkg={pkg}
                onSelect={handlePurchase}
                loading={purchasingId === pkg._id}
              />
            ))}
          </div>
        )}
      </div>

      {/* Transactions History */}
      {transactions.length > 0 && (
        <div className="glass rounded-3xl p-6 sm:p-8 space-y-4">
          <div className="flex items-center gap-2 pb-3 border-b border-ivory-300/40">
            <History size={16} className="text-champagne-500" />
            <h3 className="font-display text-lg font-bold text-charcoal-700">Recent Credit Activity</h3>
          </div>

          <div className="space-y-3">
            {transactions.map((tx) => (
              <div key={tx._id} className="flex items-center justify-between text-xs py-1.5 border-b border-ivory-200/40 last:border-0">
                <div>
                  <p className="font-semibold text-charcoal-700">{tx.description || tx.type}</p>
                  <p className="text-[11px] text-charcoal-400">{formatDate(tx.createdAt)}</p>
                </div>
                <span className={`font-bold font-mono ${tx.amount > 0 ? 'text-emerald-600' : 'text-rose-500'}`}>
                  {tx.amount > 0 ? `+${tx.amount}` : tx.amount} Credits
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
